name: Tests on push

on:
  push:
    branches: [master]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"
      - name: install node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: build frontend
        run: |
          cd streamlit_nivo_sankey/frontend/
          npm install
          npm run build
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
      - name: Replace _RELEASE flag
        run: |
          sed -i 's/_RELEASE = False/_RELEASE = True/g' ./streamlit_nivo_sankey/__init__.py
      - name: Build package
        run: python setup.py sdist bdist_wheel
